#!/bin/sh

set -eu

VERSION="${1:?version is required}"
LINUX_INTEL_SHA="${2:?x86_64 Linux sha256 is required}"
LICENSE_SHA="${3:?license sha256 is required}"
OUT_DIR="${4:?output directory is required}"

mkdir -p "${OUT_DIR}"

cat >"${OUT_DIR}/PKGBUILD" <<EOF
# shellcheck shell=bash disable=SC2034,SC2154
# Generated by scripts/render-aur-bin-files.sh
pkgname=codexctl-bin
pkgver=${VERSION}
pkgrel=1
pkgdesc='Supervise Codex sessions with a learning local brain'
arch=('x86_64')
url='https://github.com/aleadag/codexctl'
license=('MIT')
provides=('codexctl')
conflicts=('codexctl' 'codexctl-git')
source=(
  "codexctl-v\${pkgver}-x86_64-unknown-linux-musl.tar.gz::https://github.com/aleadag/codexctl/releases/download/v\${pkgver}/codexctl-v\${pkgver}-x86_64-unknown-linux-musl.tar.gz"
  "LICENSE::https://raw.githubusercontent.com/aleadag/codexctl/v\${pkgver}/LICENSE"
)
sha256sums=(
  '${LINUX_INTEL_SHA}'
  '${LICENSE_SHA}'
)

package() {
  install -Dm755 "\${srcdir}/codexctl" "\${pkgdir}/usr/bin/codexctl"
  install -Dm644 "\${srcdir}/LICENSE" "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
}
EOF

cat >"${OUT_DIR}/.SRCINFO" <<EOF
pkgbase = codexctl-bin
	pkgdesc = Supervise Codex sessions with a learning local brain
	pkgver = ${VERSION}
	pkgrel = 1
	url = https://github.com/aleadag/codexctl
	arch = x86_64
	license = MIT
	conflicts = codexctl
	conflicts = codexctl-git
	provides = codexctl
	source = codexctl-v${VERSION}-x86_64-unknown-linux-musl.tar.gz::https://github.com/aleadag/codexctl/releases/download/v${VERSION}/codexctl-v${VERSION}-x86_64-unknown-linux-musl.tar.gz
	source = LICENSE::https://raw.githubusercontent.com/aleadag/codexctl/v${VERSION}/LICENSE
	sha256sums = ${LINUX_INTEL_SHA}
	sha256sums = ${LICENSE_SHA}

pkgname = codexctl-bin
EOF
