#!/bin/sh

set -eu

VERSION="${1:?version is required}"
LINUX_INTEL_SHA="${2:?x86_64 Linux sha256 is required}"
LICENSE_SHA="${3:?license sha256 is required}"
OUT_DIR="${4:?output directory is required}"

mkdir -p "${OUT_DIR}"

cat >"${OUT_DIR}/PKGBUILD" <<EOF
# shellcheck shell=bash disable=SC2034,SC2154
# Generated by scripts/render-aur-bin-files.sh
pkgname=coding-brain-bin
pkgver=${VERSION}
pkgrel=1
pkgdesc='Local brain for supervising and learning from coding-agent activity.'
arch=('x86_64')
url='https://github.com/aleadag/coding-brain'
license=('MIT')
provides=('coding-brain')
conflicts=('coding-brain' 'coding-brain-git')
source=(
  "coding-brain-v\${pkgver}-x86_64-unknown-linux-musl.tar.gz::https://github.com/aleadag/coding-brain/releases/download/v\${pkgver}/coding-brain-v\${pkgver}-x86_64-unknown-linux-musl.tar.gz"
  "LICENSE::https://raw.githubusercontent.com/aleadag/coding-brain/v\${pkgver}/LICENSE"
)
sha256sums=(
  '${LINUX_INTEL_SHA}'
  '${LICENSE_SHA}'
)

package() {
  install -Dm755 "\${srcdir}/coding-brain" "\${pkgdir}/usr/bin/coding-brain"
  install -Dm644 "\${srcdir}/LICENSE" "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
}
EOF

cat >"${OUT_DIR}/.SRCINFO" <<EOF
pkgbase = coding-brain-bin
	pkgdesc = Local brain for supervising and learning from coding-agent activity.
	pkgver = ${VERSION}
	pkgrel = 1
	url = https://github.com/aleadag/coding-brain
	arch = x86_64
	license = MIT
	conflicts = coding-brain
	conflicts = coding-brain-git
	provides = coding-brain
	source = coding-brain-v${VERSION}-x86_64-unknown-linux-musl.tar.gz::https://github.com/aleadag/coding-brain/releases/download/v${VERSION}/coding-brain-v${VERSION}-x86_64-unknown-linux-musl.tar.gz
	source = LICENSE::https://raw.githubusercontent.com/aleadag/coding-brain/v${VERSION}/LICENSE
	sha256sums = ${LINUX_INTEL_SHA}
	sha256sums = ${LICENSE_SHA}

pkgname = coding-brain-bin
EOF
